before:
  hooks:
    - go mod download
    - go generate .
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^:pencil:"
brews:
  - tap:
      owner: clevyr
      name: homebrew-tap
    folder: Formula
dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:latest
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
      - clevyr/{{ .ProjectName }}:latest
      - clevyr/{{ .ProjectName }}:{{ .Version }}
      - clevyr/{{ .ProjectName }}:{{ .Major }}
      - clevyr/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
    use: buildx
