// Code generated by gen_template_embed.go; DO NOT EDIT.

package main

import "embed"

//go:embed "templates"
//go:embed "templates/10-before-composer/.dockerignore"
//go:embed "templates/10-before-composer/.env"
//go:embed "templates/10-before-composer/.env.example"
//go:embed "templates/10-before-composer/.nvmrc"
//go:embed "templates/10-before-composer/nova-components/.gitkeep"
var templates embed.FS
