version: "3.9"

services:
  app:
    image: clevyr/{{ .AppSlug }}/app
    build:
      args:
        INSTALL_XDEBUG: "true"
        NODE_ENV: development
      context: .
      dockerfile: docker/app/Dockerfile
      target: local-image
    env_file:
      - .env
    environment:
      DB_HOST: database
      HTTPS: "true"
      MAIL_HOST: mail
      REDIS_HOST: redis
    restart: unless-stopped
    volumes:
      - .:/app

  worker:
    extends: app
    command: ["s6-svscan", "/etc/s6/worker"]

  proxy:
    image: ghcr.io/clevyr/caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ~/.config/caddy:/data

  {{ if eq .Database "PostgreSQL" -}}
  database:
    environment:
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DATABASE"
    image: postgres:12-alpine
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

  database_test:
    environment:
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DATABASE"
    image: postgres:12-alpine
    restart: unless-stopped
  {{- else if eq .Database "MariaDB" -}}
  database:
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql

  database_test:
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: unless-stopped
  {{- end }}

  hot:
    build: docker/hot
    env_file:
      - .env
    image: clevyr/{{ .AppSlug }}/hot-reloader
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    restart: unless-stopped

  mail:
    image: ghcr.io/clevyr/mailhog
    ports:
      - 127.0.0.1:25:25
    restart: unless-stopped

volumes:
  database:
