module.exports = {
	'extends': 'stylelint-config-recommended-scss',
	'customSyntax': 'postcss-scss',
	'rules': {
		'indentation': 'tab',
		'string-quotes': null,
		'no-duplicate-selectors': true,
		'selector-combinator-space-after': 'always',
		'selector-attribute-quotes': 'always',
		'declaration-block-trailing-semicolon': 'always',
		'declaration-colon-space-before': 'never',
		'declaration-colon-space-after': 'always',
		'number-leading-zero': 'always',
		'font-weight-notation': 'numeric',
		'comment-empty-line-before': null,
		'selector-pseudo-element-colon-notation': 'single',
		'selector-pseudo-class-parentheses-space-inside': 'never',
		'media-feature-range-operator-space-before': 'always',
		'media-feature-range-operator-space-after': 'always',
		'media-feature-colon-space-before': 'never',
		'media-feature-colon-space-after': 'always',
		'max-nesting-depth': [
			4,
			{ 'ignore': ['blockless-at-rules', 'pseudo-classes'] },
		],
		'at-rule-no-unknown': [
			true,
			{
				ignoreAtRules: [
					'tailwind',
					'apply',
					'variants',
					'responsive',
					'screen',
					'media',
					'include',
					'mixin',
					'function',
					'return',
					'if',
					'else',
					'warn',
					'for',
					'use',
				],
			},
		],
	},
};
