laravel/jetstream:
  enabled: true
  version: "2.3.11"
  then:
    - run: ["php", "artisan", "jetstream:install", "inertia", "--teams"]

laravel/telescope:
  enabled: true
  version: "4.6.0"
  then:
    - run: ["cp", "vendor/laravel/telescope/stubs/TelescopeServiceProvider.stub", "app/Providers/TelescopeServiceProvider.php"]
    - run: ["php", "artisan", "telescope:install"]
    - run: ["mkdir", "-p", "public/vendor/telescope"]
    - run: ["cp", "-a", "vendor/laravel/telescope/public/.", "public/vendor/telescope"]

joelbutcher/socialstream:
  enabled: true
  version: "3.1.3"
  then:
    - run: ["php", "artisan", "socialstream:install"]

laravel/nova:
  enabled: true
  version: "3.27.0"
  then:
    - run: ["php", "artisan", "nova:install"]

laravel/spark-paddle:
  enabled: true
  version: "1.1.5"
  then:
    - run: ["php", "artisan", "spark:install"]

clevyr/nova-page-builder:
  enabled: true
  then:
    - run: ["php", "artisan", "vendor:publish", "--tag=clevyr-nova-page-builder"]

ukfast/laravel-health-check:
  enabled: true
  version: "1.13.0"

backpack/crud: {}

clevyr/backpack-page-builder: {}

superbalist/laravel-google-cloud-storage: {}

nunomaduro/larastan: {}
