laravel/jetstream:
  enabled: true
  version: "2.10.3"
  priority: 100
  then:
    - run: ["php", "artisan", "jetstream:install", "inertia"]

laravel/telescope:
  enabled: true
  version: "4.9.1"
  then:
    - copy:
      src: "vendor/laravel/telescope/stubs/TelescopeServiceProvider.stub"
      dst: "app/Providers/TelescopeServiceProvider.php"
    - run: ["php", "artisan", "telescope:install"]
    - run: ["mkdir", "-p", "public/vendor/telescope"]
    - copy:
        src: "vendor/laravel/telescope/public/."
        dst: "public/vendor/telescope"

joelbutcher/socialstream:
  enabled: true
  version: "3.7.0"
  then:
    - run: ["php", "artisan", "socialstream:install", "inertia"]

laravel/nova:
  enabled: true
  version: "4.12.14"
  then:
    - run: ["php", "artisan", "nova:install"]

laravel/spark-paddle:
  enabled: true
  version: "2.1.2"
  then:
    - run: ["php", "artisan", "spark:install"]

clevyr/nova-page-builder:
  enabled: true
  version: "4.1.0"
  then:
    - run: ["php", "artisan", "vendor:publish", "--tag=clevyr-nova-page-builder"]
    - run: ["php", "artisan", "vendor:publish", "--tag=filemanager-config"]
    - run: ["php", "artisan", "vendor:publish", '--provider=Emilianotisato\NovaTinyMCE\FieldServiceProvider']

clevyr/nova-blog:
  enabled: true
  version: "4.0.4"
  then:
    - run: ["php", "artisan", "vendor:publish", "--tag=clevyr-nova-blog"]

ans-group/laravel-health-check:
  enabled: false
  version: "1.13.4"

spatie/laravel-google-cloud-storage:
  enabled: true
  version: "2.0.3"

nunomaduro/larastan:
  enabled: true
  dev: true
  version: "2.1.12"

laravel/dusk:
  enabled: true
  dev: true
  version: "6.25.1"
  then:
    - run: ["php", "artisan", "dusk:install"]

pestphp/pest:
  enabled: true
  dev: true

pestphp/pest-plugin-laravel:
  enabled: true
  dev: true
  then:
    - run: ["php", "artisan", "pest:install"]
