laravel/jetstream:
  enabled: true
  version: "2.12.3"
  priority: 100
  then:
    - run: ["php", "artisan", "jetstream:install", "inertia"]

laravel/telescope:
  enabled: true
  version: "4.9.3"
  then:
    - copy:
      src: "vendor/laravel/telescope/stubs/TelescopeServiceProvider.stub"
      dst: "app/Providers/TelescopeServiceProvider.php"
    - run: ["php", "artisan", "telescope:install"]
    - run: ["mkdir", "-p", "public/vendor/telescope"]
    - copy:
        src: "vendor/laravel/telescope/public/."
        dst: "public/vendor/telescope"

joelbutcher/socialstream:
  enabled: true
  version: "3.8.0"
  then:
    - run: ["php", "artisan", "socialstream:install", "--stack=inertia"]

laravel/nova:
  enabled: true
  version: "4.15.2"
  then:
    - run: ["php", "artisan", "nova:install"]

laravel/horizon:
  enabled: true
  version: "5.10.2"
  then:
    - run: ["composer", "require", "laravel/horizon"]
    - run: ["php", "artisan", "horizon:install"]

laravel/spark-paddle:
  enabled: false
  version: "2.1.10"
  then:
    - run: ["php", "artisan", "spark:install"]

clevyr/laravel-geocoder:
  enabled: true
  version: "0.1.1"
  then:
    - run: ["php", "artisan", "vendor:publish", "--provider=Clevyr\\LaravelGeocoder\\LaravelGeocoderServiceProvider"]

clevyr/laravel-twilio-channel:
  enabled: true
  version: "0.2.0"
  then:
    - run: ["php", "artisan", "vendor:publish", "--provider=Clevyr\\LaravelTwilioChannel\\LaravelTwilioChannelServiceProvider"]

clevyr/laravel-simple-feedback-form:
  enabled: true
  version: "0.2.1"
  then:
    - run: ["php", "artisan", "vendor:publish", "--tag=laravel-simple-feedback-form-config"]
    - run: ["php", "artisan", "vendor:publish", "--provider=Clevyr\\FeedbackForm\\FeedbackFormServiceProvider"]

clevyr/nova-page-builder:
  enabled: true
  version: "4.1.1"
  then:
    - run: ["php", "artisan", "vendor:publish", "--tag=clevyr-nova-page-builder"]
    - run: ["php", "artisan", "vendor:publish", "--tag=filemanager-config"]
    - run: ["php", "artisan", "vendor:publish", '--provider=Emilianotisato\NovaTinyMCE\FieldServiceProvider']

clevyr/nova-blog:
  enabled: true
  version: "4.0.6"
  then:
    - run: ["php", "artisan", "vendor:publish", "--tag=clevyr-nova-blog"]

ans-group/laravel-health-check:
  enabled: true
  version: "1.13.4"

spatie/laravel-google-cloud-storage:
  enabled: true
  version: "2.0.5"

nunomaduro/larastan:
  enabled: true
  dev: true
  version: "2.2.0"

laravel/dusk:
  enabled: true
  dev: true
  version: "7.1.1"
  then:
    - run: ["php", "artisan", "dusk:install"]

pestphp/pest:
  enabled: true
  dev: true

pestphp/pest-plugin-laravel:
  enabled: true
  dev: true
  then:
    - run: ["php", "artisan", "pest:install", "--no-interaction"]
