bcmath:
  enabled: true

calendar: {}

exif:
  enabled: true

gd:
  enabled: true

imagick: {}

mosquitto: {}

mysql: {}

opcache:
  enabled: true

pcntl:
  enabled: true

pgsql: {}

redis:
  enabled: true

sqlsrv: {}

xdebug:
  enabled: true

zip:
  enabled: true
