// Code generated by internal/generators/template_embed.go; DO NOT EDIT.

package templates

import "embed"

//go:embed "all:laravel-10-before-composer"
var embedLaravel10BeforeComposer embed.FS

var Laravel10BeforeComposer = Template{
	Name:  "laravel-10-before-composer",
	Embed: embedLaravel10BeforeComposer,
	Modes: map[string]int32{
		"laravel-10-before-composer/docker/app/rootfs/entrypoint":                     0755,
		"laravel-10-before-composer/docker/app/rootfs/etc/s6/app/nginx/run":           0755,
		"laravel-10-before-composer/docker/app/rootfs/etc/s6/app/php-fpm/run":         0755,
		"laravel-10-before-composer/docker/app/rootfs/etc/s6/worker/cron/run":         0755,
		"laravel-10-before-composer/docker/app/rootfs/etc/s6/worker/queue-runner/run": 0755,
		"laravel-10-before-composer/docker/app/rootfs/health-check":                   0755,
		"laravel-10-before-composer/docker/hot/rootfs/entrypoint":                     0755,
	},
}

//go:embed "all:laravel-20-after-composer"
var embedLaravel20AfterComposer embed.FS

var Laravel20AfterComposer = Template{
	Name:  "laravel-20-after-composer",
	Embed: embedLaravel20AfterComposer,
	Modes: map[string]int32{},
}
